services:
  mongo:
    image: mongo:7
    container_name: restaurant_reviews_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: restaurant_reviews

volumes:
  mongo_data:
